version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "mjun0812"
    assignees:
      - "mjun0812"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      iconify:
        patterns:
          - "@iconify-json/*"
          - "astro-icon"
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "mjun0812"
    assignees:
      - "mjun0812"
